# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f331b937482e985d810625e7709467294f85140dc07ad8aca26319b377df12e7e9df24dafd8b8fb4662b949d3e68c77e81aace9d6868f7e7826cb433489694

test:
  secret_key_base: 5e887ac9c90617b8e98efb851cc2f3420685eda1318f1edad8a877e5a6ca0975aafaff85f245700fdf6522ade103f1af7f4eb36e8b696b7afa0feae587aff183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
